language: elixir

elixir: '1.6.0'
otp_release: '20.2.2'

addons:
  postgresql: '9.6'
  apt:
    packages:
    - build-essential
    - gdal-bin
    - postgresql-9.6-postgis-2.3
    - erlang-dev

services:
  - postgresql

script:
  - mix test --trace --cover
