language: elixir

elixir:
  - '1.6.0'
otp_release:
  - '20.2.2'

addons:
  postgresql: '9.5'

services:
  - postgresql

env:
  - MIX_ENV=test

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa -yes
  - sudo apt-get update
  - sudo apt-get install gdal-bin -y
  - sudo apt-get install build-essential -y
  - sudo apt-get install erlang-dev -y
  - sudo apt-get install -y postgresql-9.5-postgis-2.3

before_script:
  - psql -U postgres -c "create extension postgis"
  - mix do ecto.create, ecto.migrate

script:
  - mix coveralls.travis
