language: elixir

elixir:
  - '1.6'

addons:
  postgresql: '9.6'
  apt:
    packages:
    - build-essential
    - gdal-bin
    - postgresql-9.6-postgis-2.3
    - erlang-dev

services:
  - postgresql

env:
  - MIX_ENV=test

before_script:
  - psql -U postgres -c "create extension postgis"

script:
  - mix test --trace --cover
