language: elixir

elixir:
  - '1.5'
otp_release:
  - '20.1'

addons:
  postgresql: '9.5'

services:
  - postgresql

env:
  - MIX_ENV=test

before_install:
  - sudo apt-get install build-essential
  - sudo apt-get install erlang-dev

before_script:
  - psql -U postgres -c "create extension postgis"
  - mix do ecto.create, ecto.migrate

script:
  - mix coveralls.travis
