language: elixir

elixir:
  - '1.6.0'
otp_release:
  - '20.2.2'

addons:
  postgresql: '9.5'
  apt:
    packages:
    - build-essential
    - gdal-bin
    - postgresql-9.5-postgis-2.3
    - erlang-dev

services:
  - postgresql

env:
  - MIX_ENV=test

before_script:
  - psql -U postgres -c "create extension postgis"
  - mix do ecto.create, ecto.migrate

script:
  - mix coveralls.travis
