language: elixir

elixir:
  - '1.7'
otp_release:
  - '21.1.1'

addons:
  postgresql: '9.6'
  apt:
    packages:
    - build-essential
    - gdal-bin
    - postgresql-9.6-postgis-2.3
    - erlang-dev

services:
  - postgresql

env:
  - MIX_ENV=test

before_script:
  - psql -U postgres -c "create extension postgis"

script:
  - mix do deps.get, deps.compile, clean, compile, ecto.drop, ecto.create, ecto.migrate, coveralls.travis --trace
