language: elixir

elixir:
  - 1.4.1

addons:
  postgresql: '9.5'

services:
  - postgresql

env:
  - MIX_ENV=test

before_script:
  - mix do ecto.create, ecto.migrate

script:
  - mix coveralls.travis
