language: elixir

elixir:
  - '1.6.0'
otp_release:
  - '20.2.2'

addons:
  postgresql: '9.5'

services:
  - postgresql

env:
  - MIX_ENV=test

sudo: true

before_install:
  - sudo apt-get install build-essential -y
  - sudo apt-get install erlang-dev -y
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install gdal-bin -y

before_script:
  - psql -U postgres -c "create extension postgis"
  - mix do ecto.create, ecto.migrate

script:
  - mix coveralls.travis
