use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# PlenarioWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :plenario, PlenarioWeb.Endpoint,
  http: [
    port: 8888
  ],
  url: [
    host: "dev.plenar.io",
    port: 443,
    scheme: "https"
  ],
  cache_static_manifest: "priv/static/cache_manifest.json"


# Do not print debug messages in production
config :logger, level: :info

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
config :phoenix, :serve_endpoints, true


# Finally import the config/prod.secret.exs
# which should be versioned separately.
import_config "prod.secret.exs"
